export * from 'tamagui'
export * from '@tamagui/toast'
export * from './MyComponent'
export { config } from '@patilive/config'
export * from './CustomToast'
export * from './NativeToast'
export * from './SwitchThemeButton'
export * from './SwitchRouterButton'
export * from './Patibutton'
